---

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "unzip"]
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create the backend app folder
  become: yes
  file:
    path: /home/ubuntu/nodeapp
    state: directory

- name: "Copy backend build to server"
  become: yes
  unarchive:
    src: /tmp/backend.zip
    dest: /home/ubuntu/nodeapp/
    owner: ubuntu

- name: "Install NPM dependencies"
  become: yes
  shell:
    cmd: npm install
    chdir: /home/ubuntu/nodeapp

- name: "Build the app"
  shell:
    cmd: npm run build
    chdir: /home/ubuntu/nodeapp

- name: start pm2 process
  command: 'pm2 start /home/ubuntu/nodeapp/dist/main.js --name nodeapp'
  environment:
    NODE_ENV: "production"
    TYPEORM_CONNECTION: $TYPEORM_CONNECTION
    TYPEORM_HOST: $TYPEORM_HOST
    TYPEORM_PORT: $TYPEORM_PORT
    TYPEORM_USERNAME: $TYPEORM_USERNAME
    TYPEORM_PASSWORD: $TYPEORM_PASSWORD
    TYPEORM_DATABASE: $TYPEORM_DATABASE
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_ENTITIES: ./src/modules/**/*.entity.ts